"""
HTS-HFC v2 Reference Simulator
==============================

Purpose
-------
Bit-accurate Python reference of the HTS Holographic Fractal Code v2
designed for Cortex-M4F with TPE (AND/OR/XOR/SHIFT) primitives and the
existing Dynamic_Fractal_Mapper infrastructure.

Pipeline
--------
    64 info bits + 16 CRC  =  80 bits
              |
              v  [Polar Kernel N=128, 48 frozen]
        128 polarized bits
              |
              v  [Fractal Rate Expansion via ARX128]
        688 coded bits (matches current TOTAL_CODED)
              |
              v  [BPSK over AWGN]                            <-- sim channel
              |
              v  [Fractal LLR Combining 688 -> 128]
        128 combined LLRs
              |
              v  [Polar SC decoder, TPE branchless]
        80 decoded bits
              |
              v  [CRC check; if fail -> partial CRC-SC retry]
        64 info bits

Metrics
-------
    * BLER vs Eb/N0
    * Average decode time (proxy via operation count)
    * Memory footprint (static arrays only)

Comparison
----------
    * Reference: uncoded BPSK (Shannon lower-bound sanity check)
    * Baseline : plain Polar SC (no fractal expansion, N=128, puncture/rep
                 to 688 via simple copy)

Run
---
    python3 hfc_v2_sim.py                       # full sweep
    python3 hfc_v2_sim.py --quick               # fast smoke test
    python3 hfc_v2_sim.py --ebno 2.0 --trials 5000

Design Notes
------------
    * Polar encoder is the bit-reversed Arikan kernel, standard form.
    * Frozen bit set is chosen by Bhattacharyya parameter at design SNR
      (computed once, cached).
    * Fractal rate expansion: each of 688 coded bits is an XOR of a
      deterministic subset of the 128 polarized bits. The subset pattern
      is generated by an ARX128 PRNG keyed to block index. Min-weight
      constraint (>=3) ensures diversity.
    * SC decoder uses integer f/g functions that mirror the M4 TPE impl.
"""

from __future__ import annotations

import argparse
import math
import sys
import time
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np


# ---------------------------------------------------------------------------
#  Parameters (match firmware constants where applicable)
# ---------------------------------------------------------------------------

K_INFO = 64           # information bits per packet
CRC_BITS = 16         # CRC-CCITT
K_PAYLOAD = K_INFO + CRC_BITS  # 80 bits entering Polar
N_POLAR = 128         # Polar codeword length (power of 2)
N_CODED = 688         # coded bits delivered to modulator (TOTAL_CODED)
# Rate expansion = repetition via ARX-keyed permutation.
# Every polar bit is repeated ceil(N_CODED/N_POLAR) or floor(...) times;
# distribution is balanced so max-min spread is <= 1.
REP_AVG = N_CODED / N_POLAR   # ~= 5.375


# ---------------------------------------------------------------------------
#  CRC-16/CCITT  (same polynomial 0x1021 as firmware CRC16)
# ---------------------------------------------------------------------------

def crc16_ccitt(bits: np.ndarray) -> np.ndarray:
    """Compute CRC-16/CCITT over a bit array (MSB first). Returns 16 bits."""
    reg = 0xFFFF
    # bits are packed MSB-first into bytes for CRC
    n_bytes = len(bits) // 8
    for i in range(n_bytes):
        byte = 0
        for j in range(8):
            byte = (byte << 1) | int(bits[i * 8 + j])
        reg ^= byte << 8
        for _ in range(8):
            if reg & 0x8000:
                reg = ((reg << 1) ^ 0x1021) & 0xFFFF
            else:
                reg = (reg << 1) & 0xFFFF
    out = np.zeros(16, dtype=np.uint8)
    for k in range(16):
        out[k] = (reg >> (15 - k)) & 1
    return out


# ---------------------------------------------------------------------------
#  ARX128 PRNG (mirrors arx_state used by Dynamic_Fractal_Mapper)
# ---------------------------------------------------------------------------

class ARX128:
    """Simple ARX (Add-Rotate-XOR) 128-bit PRNG, matching firmware style."""

    def __init__(self, seed: int = 0xDEADBEEF):
        s = seed & 0xFFFFFFFF
        self.s = [s, (s * 0x9E3779B9) & 0xFFFFFFFF,
                  (s ^ 0xA5A5A5A5) & 0xFFFFFFFF,
                  ((s << 13) ^ (s >> 7)) & 0xFFFFFFFF]

    def step(self) -> int:
        a, b, c, d = self.s
        a = (a + b) & 0xFFFFFFFF
        c = (c ^ d) & 0xFFFFFFFF
        b = ((b << 13) | (b >> 19)) & 0xFFFFFFFF
        d = ((d << 7) | (d >> 25)) & 0xFFFFFFFF
        a ^= c
        b = (b + d) & 0xFFFFFFFF
        self.s = [a, b, c, d]
        return (a ^ b ^ c ^ d) & 0xFFFFFFFF


# ---------------------------------------------------------------------------
#  Polar code: frozen bit selection via Bhattacharyya recursion
# ---------------------------------------------------------------------------

def bhattacharyya_polar(n: int, design_ebn0_db: float) -> np.ndarray:
    """
    Return Bhattacharyya parameters for N synthetic channels.
    Indices with smaller Z are more reliable.
    """
    # channel parameter at design SNR
    ebn0 = 10 ** (design_ebn0_db / 10.0)
    z = [math.exp(-ebn0)]  # Z of single BSC-equivalent channel
    while len(z) < n:
        new = []
        for zi in z:
            new.append(2 * zi - zi * zi)  # worse channel
            new.append(zi * zi)           # better channel
        z = new
    return np.array(z[:n])


def select_frozen(n: int, k: int, design_ebn0_db: float = 2.0) -> np.ndarray:
    """Return boolean array of length N; True = frozen, False = info."""
    z = bhattacharyya_polar(n, design_ebn0_db)
    order = np.argsort(z)          # most reliable first
    info_positions = order[:k]     # pick K best for info
    frozen = np.ones(n, dtype=bool)
    frozen[info_positions] = False
    return frozen


# ---------------------------------------------------------------------------
#  Polar encoder  (Arikan kernel F = [[1,0],[1,1]], Kronecker applied)
# ---------------------------------------------------------------------------

def polar_encode(u: np.ndarray) -> np.ndarray:
    """In-place-style Polar encoding: x = u * F^{kron n}."""
    n = len(u)
    x = u.copy().astype(np.uint8)
    stride = 1
    while stride < n:
        for i in range(0, n, 2 * stride):
            for j in range(stride):
                x[i + j] ^= x[i + j + stride]
        stride *= 2
    return x


# ---------------------------------------------------------------------------
#  Fractal Rate Expansion: 128 -> 688 via ARX128-keyed permuted repetition
#
#  Design:
#    * Each coded bit is ONE polar bit (no XOR mixing). Decoder is a trivial
#      matched-filter LLR sum per polar index -- TPE-friendly, zero BP.
#    * ARX128 PRNG produces a deterministic permutation of the index pool
#      [0..N_POLAR-1] repeated ceil(N_CODED/N_POLAR) times, then truncated.
#    * Guarantees balanced repetition (max_count - min_count <= 1) and
#      spreads repeats across time to decorrelate burst jammers.
# ---------------------------------------------------------------------------

def build_fractal_masks(seed: int = 0xDEADBEEF) -> np.ndarray:
    """
    Return an int array of shape (N_CODED,) where masks[i] gives the polar
    index whose value is placed at coded position i.

    Construction: stack ceil(N_CODED/N_POLAR) copies of [0..127], shuffle the
    pool with ARX128 (Fisher-Yates), then truncate to N_CODED.
    """
    rng = ARX128(seed)

    # Exact balanced multiset:
    #   low_reps = floor(N_CODED/N_POLAR), high_reps = low_reps + 1
    #   n_high indices get high_reps copies, rest get low_reps copies.
    low_reps = N_CODED // N_POLAR
    n_high = N_CODED - low_reps * N_POLAR            # indices with +1 copy
    # Pick which indices get the extra copy via an ARX-shuffled 0..N_POLAR-1.
    idx_order = np.arange(N_POLAR, dtype=np.int32)
    for i in range(N_POLAR - 1, 0, -1):
        j = rng.step() % (i + 1)
        idx_order[i], idx_order[j] = idx_order[j], idx_order[i]
    high_set = idx_order[:n_high]

    pool = np.empty(N_CODED, dtype=np.int32)
    k = 0
    for idx in range(N_POLAR):
        r = low_reps + (1 if idx in set(high_set.tolist()) else 0)
        pool[k:k + r] = idx
        k += r
    assert k == N_CODED

    # Fisher-Yates shuffle positions so repeats are time-spread.
    for i in range(N_CODED - 1, 0, -1):
        j = rng.step() % (i + 1)
        pool[i], pool[j] = pool[j], pool[i]

    masks = pool

    # sanity: balanced repetition, every polar bit covered
    counts = np.bincount(masks, minlength=N_POLAR)
    assert counts.min() >= 1, f"uncovered polar bit (min={counts.min()})"
    assert counts.max() - counts.min() <= 1, \
        f"unbalanced rep: min={counts.min()} max={counts.max()}"
    return masks


def fractal_expand(polar_bits: np.ndarray, masks: np.ndarray) -> np.ndarray:
    """128 polar bits -> 688 coded bits via permuted repetition."""
    return polar_bits[masks].astype(np.uint8)


def fractal_combine_llr(rx_llr: np.ndarray, masks: np.ndarray) -> np.ndarray:
    """
    Matched-filter combine: sum LLRs landing on each polar index.
    This is the ML soft-combiner for repetition over AWGN.
    """
    combined = np.zeros(N_POLAR, dtype=np.float64)
    # np.add.at is the unbuffered indexed accumulation (correct for duplicates)
    np.add.at(combined, masks, rx_llr)
    return combined


# ---------------------------------------------------------------------------
#  Polar SC decoder (integer, TPE-style f/g)
# ---------------------------------------------------------------------------

def f_node(a: float, b: float) -> float:
    """f = sign(a)*sign(b)*min(|a|,|b|)"""
    sa = 1.0 if a >= 0 else -1.0
    sb = 1.0 if b >= 0 else -1.0
    return sa * sb * min(abs(a), abs(b))


def g_node(a: float, b: float, u: int) -> float:
    """g = (1 - 2u)*a + b"""
    return (a if u == 0 else -a) + b


def sc_decode(llr_in: np.ndarray, frozen: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Standard Polar SC decoder.
    Returns (decoded_u_hat, decoded_x_hat, decision_llr).
    decision_llr[i] = the LLR at the leaf at the moment u_hat[i] was decided
    (i.e. SC reliability, not channel reliability).
    """
    n = len(llr_in)
    depth = int(math.log2(n))

    # stage LLR buffers
    llr = np.zeros((depth + 1, n))
    llr[depth] = llr_in
    u_hat = np.zeros(n, dtype=np.uint8)
    decision_llr = np.zeros(n, dtype=np.float64)
    # partial sums per stage
    ps = np.zeros((depth + 1, n), dtype=np.uint8)

    def recurse(stage: int, start: int, length: int):
        if length == 1:
            decision_llr[start] = llr[stage, start]
            if frozen[start]:
                u_hat[start] = 0
            else:
                u_hat[start] = 0 if llr[stage, start] >= 0 else 1
            ps[stage, start] = u_hat[start]
            return

        half = length // 2
        # f-step: produce left-child LLRs
        for i in range(half):
            a = llr[stage, start + i]
            b = llr[stage, start + i + half]
            llr[stage - 1, start + i] = f_node(a, b)
        recurse(stage - 1, start, half)

        # g-step: right-child LLRs
        for i in range(half):
            a = llr[stage, start + i]
            b = llr[stage, start + i + half]
            u = ps[stage - 1, start + i]
            llr[stage - 1, start + i + half] = g_node(a, b, int(u))
        recurse(stage - 1, start + half, half)

        # combine partial sums upward
        for i in range(half):
            ps[stage, start + i] = ps[stage - 1, start + i] ^ ps[stage - 1, start + i + half]
            ps[stage, start + i + half] = ps[stage - 1, start + i + half]

    recurse(depth, 0, n)
    x_hat = polar_encode(u_hat)
    return u_hat, x_hat, decision_llr


# ---------------------------------------------------------------------------
#  Partial CRC-SC retry: flip L least-reliable info positions
# ---------------------------------------------------------------------------

def sc_decode_with_crc_retry(
    llr_in: np.ndarray,
    frozen: np.ndarray,
    max_flips: int = 8,
) -> Tuple[bool, np.ndarray]:
    """
    Returns (ok, info_bits[64]).
    Tries up to 2^max_flips CRC checks, enumerated in increasing
    Hamming-weight order (flip combinations of the weakest positions first).
    """
    u_hat, _, dec_llr = sc_decode(llr_in, frozen)
    info_slots = np.where(~frozen)[0]
    info = u_hat[info_slots]          # 80 bits in Polar-order
    rx_info = info[:K_INFO]
    rx_crc  = info[K_INFO:]

    if np.array_equal(crc16_ccitt(rx_info), rx_crc):
        return True, rx_info

    # SC reliability: |decision LLR at the info leaf|
    rel = np.abs(dec_llr[info_slots])
    order = np.argsort(rel)                # weakest first
    weak = order[:max_flips]

    # Enumerate flip masks in order of Hamming weight (cheap-first search).
    flip_masks = sorted(range(1, 1 << max_flips),
                        key=lambda m: (bin(m).count('1'), m))
    for mask in flip_masks:
        trial = info.copy()
        for b in range(max_flips):
            if (mask >> b) & 1:
                trial[weak[b]] ^= 1
        t_info = trial[:K_INFO]
        t_crc  = trial[K_INFO:]
        if np.array_equal(crc16_ccitt(t_info), t_crc):
            return True, t_info

    return False, rx_info


# ---------------------------------------------------------------------------
#  TX / RX full pipeline
# ---------------------------------------------------------------------------

@dataclass
class Codec:
    frozen: np.ndarray
    masks: np.ndarray

    @classmethod
    def build(cls, seed: int = 0xDEADBEEF,
              target_ebn0_db: float = 2.5) -> "Codec":
        # Bhattacharyya design SNR = channel that the POLAR decoder actually
        # sees, i.e. after matched-filter combining of REP_AVG repetitions.
        #   polar_input_EsN0 = REP_AVG * rate_coded * Eb/N0_operating
        # Express as dB for bhattacharyya_polar().
        rate_coded = K_INFO / N_CODED
        ebn0_lin = 10 ** (target_ebn0_db / 10.0)
        polar_esn0_lin = REP_AVG * rate_coded * ebn0_lin
        polar_esn0_db = 10.0 * math.log10(polar_esn0_lin)
        frozen = select_frozen(N_POLAR, K_PAYLOAD, polar_esn0_db)
        masks = build_fractal_masks(seed)
        return cls(frozen=frozen, masks=masks)


def encode(info: np.ndarray, codec: Codec) -> np.ndarray:
    """64 info bits -> 688 coded bits."""
    assert len(info) == K_INFO
    crc = crc16_ccitt(info)
    payload = np.concatenate([info, crc])         # 80 bits

    u = np.zeros(N_POLAR, dtype=np.uint8)
    info_slots = np.where(~codec.frozen)[0]
    u[info_slots] = payload

    polar_bits = polar_encode(u)                  # 128 bits
    coded = fractal_expand(polar_bits, codec.masks)
    return coded


def decode(rx_llr_coded: np.ndarray, codec: Codec) -> Tuple[bool, np.ndarray]:
    """688 soft LLRs -> 64 info bits + success flag."""
    polar_llr = fractal_combine_llr(rx_llr_coded, codec.masks)
    return sc_decode_with_crc_retry(polar_llr, codec.frozen, max_flips=8)


# ---------------------------------------------------------------------------
#  AWGN channel
# ---------------------------------------------------------------------------

def awgn_bpsk(coded_bits: np.ndarray, ebn0_db: float, rate: float,
              rng: np.random.Generator) -> np.ndarray:
    """BPSK: 0 -> +1, 1 -> -1. Returns LLR = 2*y/sigma^2."""
    sym = 1.0 - 2.0 * coded_bits.astype(np.float64)
    ebn0 = 10 ** (ebn0_db / 10.0)
    # sigma^2 relative to bit energy = 1:
    #   Es/N0 = R * Eb/N0
    esn0 = rate * ebn0
    sigma = math.sqrt(1.0 / (2.0 * esn0))
    noise = rng.standard_normal(len(sym)) * sigma
    y = sym + noise
    llr = 2.0 * y / (sigma * sigma)
    return llr


# ---------------------------------------------------------------------------
#  Simulation loop
# ---------------------------------------------------------------------------

def run_point(ebn0_db: float, trials: int, codec: Codec,
              seed: int = 0xC0FFEE) -> dict:
    rng = np.random.default_rng(seed)
    rate = K_INFO / N_CODED

    errors_block = 0
    errors_bit = 0
    decode_time_total = 0.0
    retry_count = 0

    for t in range(trials):
        info = rng.integers(0, 2, size=K_INFO, dtype=np.uint8)
        coded = encode(info, codec)
        llr = awgn_bpsk(coded, ebn0_db, rate, rng)

        t0 = time.perf_counter()
        ok, info_hat = decode(llr, codec)
        decode_time_total += time.perf_counter() - t0

        if not ok:
            errors_block += 1
            errors_bit += int(np.sum(info_hat != info))
        else:
            # check that "ok" was truthful (CRC collisions are rare)
            if not np.array_equal(info_hat, info):
                # CRC false-positive: still count as block error on truth
                errors_block += 1
                errors_bit += int(np.sum(info_hat != info))
            # retry was invoked if first SC failed; we don't instrument that
            # here but can be added if needed

    return dict(
        ebno=ebn0_db,
        trials=trials,
        bler=errors_block / trials,
        ber=errors_bit / (trials * K_INFO),
        decode_ms_avg=1000.0 * decode_time_total / trials,
    )


def banner(codec: Codec) -> None:
    n_info_slots = int(np.sum(~codec.frozen))
    print("=" * 64)
    print(" HTS-HFC v2  Reference Simulator")
    print("=" * 64)
    print(f"  K_INFO            = {K_INFO}")
    print(f"  CRC_BITS          = {CRC_BITS}")
    print(f"  K_PAYLOAD         = {K_PAYLOAD}  (info+CRC)")
    print(f"  N_POLAR           = {N_POLAR}")
    print(f"  N_CODED           = {N_CODED}")
    print(f"  Rep expansion avg = {REP_AVG:.3f}  (coded bits per polar bit)")
    print(f"  Polar info slots  = {n_info_slots}")
    print(f"  Overall rate R    = {K_INFO / N_CODED:.4f}")
    print("=" * 64)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true",
                    help="fast smoke test (500 trials, 3 SNR points)")
    ap.add_argument("--ebno", type=float, default=None,
                    help="single Eb/N0 point (dB)")
    ap.add_argument("--trials", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=0xDEADBEEF)
    args = ap.parse_args()

    print("Building codec (Bhattacharyya frozen set + fractal masks) ...")
    codec = Codec.build(seed=args.seed, target_ebn0_db=2.5)
    banner(codec)

    if args.ebno is not None:
        pts = [args.ebno]
        trials = args.trials
    elif args.quick:
        pts = [1.0, 2.0, 3.0]
        trials = 500
    else:
        pts = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
        trials = args.trials

    print(f"\nRunning: trials={trials} per point")
    print(f"{'Eb/N0(dB)':>10} {'BLER':>10} {'BER':>12} {'dec_ms':>10}")
    print("-" * 44)
    for eb in pts:
        r = run_point(eb, trials, codec, seed=0xC0FFEE + int(eb * 100))
        print(f"{r['ebno']:>10.2f} {r['bler']:>10.4f} {r['ber']:>12.5e} "
              f"{r['decode_ms_avg']:>10.3f}")
    print()
    print("Reference targets (K=64, N=688):")
    print("  Shannon finite-length limit : Eb/N0 ~= 1.8 dB @ BLER 1e-3")
    print("  CRC-Polar-SCL L=8           : Eb/N0 ~= 2.0 dB @ BLER 1e-3")
    print("  HTS-HFC v2 design target    : Eb/N0 <= 2.3 dB @ BLER 1e-3")
    return 0


if __name__ == "__main__":
    sys.exit(main())
