"""
HTS-HFC v2 Reference Simulator
==============================

Purpose
-------
Bit-accurate Python reference of the HTS Holographic Fractal Code v2
designed for Cortex-M4F with TPE (AND/OR/XOR/SHIFT) primitives and the
existing Dynamic_Fractal_Mapper infrastructure.

Pipeline
--------
    64 info bits + 16 CRC  =  80 bits
              |
              v  [Polar Kernel N=128, 48 frozen]
        128 polarized bits
              |
              v  [Fractal Rate Expansion via ARX128]
        688 coded bits (matches current TOTAL_CODED)
              |
              v  [BPSK over AWGN]                            <-- sim channel
              |
              v  [Fractal LLR Combining 688 -> 128]
        128 combined LLRs
              |
              v  [Polar SC decoder, TPE branchless]
        80 decoded bits
              |
              v  [CRC check; if fail -> partial CRC-SC retry]
        64 info bits

Metrics
-------
    * BLER vs Eb/N0
    * Average decode time (proxy via operation count)
    * Memory footprint (static arrays only)

Comparison
----------
    * Reference: uncoded BPSK (Shannon lower-bound sanity check)
    * Baseline : plain Polar SC (no fractal expansion, N=128, puncture/rep
                 to 688 via simple copy)

Run
---
    python3 hfc_v2_sim.py                       # full sweep
    python3 hfc_v2_sim.py --quick               # fast smoke test
    python3 hfc_v2_sim.py --ebno 2.0 --trials 5000

Design Notes
------------
    * Polar encoder is the bit-reversed Arikan kernel, standard form.
    * Frozen bit set is chosen by Bhattacharyya parameter at design SNR
      (computed once, cached).
    * Fractal rate expansion: each of 688 coded bits is an XOR of a
      deterministic subset of the 128 polarized bits. The subset pattern
      is generated by an ARX128 PRNG keyed to block index. Min-weight
      constraint (>=3) ensures diversity.
    * SC decoder uses integer f/g functions that mirror the M4 TPE impl.
"""

from __future__ import annotations

import argparse
import math
import sys
import time
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np


# ---------------------------------------------------------------------------
#  Parameters (match firmware constants where applicable)
# ---------------------------------------------------------------------------

K_INFO = 64           # information bits per packet
CRC_BITS = 16         # CRC-CCITT
K_PAYLOAD = K_INFO + CRC_BITS  # 80 bits entering inner code
N_POLAR = 128         # Inner code length (power of 2 for Polar)
N_CODED = 688         # coded bits delivered to modulator (TOTAL_CODED)
REP_AVG = N_CODED / N_POLAR   # recomputed by configure_dimensions()


def configure_dimensions(n_inner: int) -> None:
    """Reconfigure module-level dimensions for multi-architecture comparison."""
    global N_POLAR, REP_AVG
    N_POLAR = n_inner
    REP_AVG = N_CODED / N_POLAR


# ---------------------------------------------------------------------------
#  CRC-16/CCITT  (same polynomial 0x1021 as firmware CRC16)
# ---------------------------------------------------------------------------

def crc16_ccitt(bits: np.ndarray) -> np.ndarray:
    """Compute CRC-16/CCITT over a bit array (MSB first). Returns 16 bits."""
    reg = 0xFFFF
    # bits are packed MSB-first into bytes for CRC
    n_bytes = len(bits) // 8
    for i in range(n_bytes):
        byte = 0
        for j in range(8):
            byte = (byte << 1) | int(bits[i * 8 + j])
        reg ^= byte << 8
        for _ in range(8):
            if reg & 0x8000:
                reg = ((reg << 1) ^ 0x1021) & 0xFFFF
            else:
                reg = (reg << 1) & 0xFFFF
    out = np.zeros(16, dtype=np.uint8)
    for k in range(16):
        out[k] = (reg >> (15 - k)) & 1
    return out


# ---------------------------------------------------------------------------
#  ARX128 PRNG (mirrors arx_state used by Dynamic_Fractal_Mapper)
# ---------------------------------------------------------------------------

class ARX128:
    """Simple ARX (Add-Rotate-XOR) 128-bit PRNG, matching firmware style."""

    def __init__(self, seed: int = 0xDEADBEEF):
        s = seed & 0xFFFFFFFF
        self.s = [s, (s * 0x9E3779B9) & 0xFFFFFFFF,
                  (s ^ 0xA5A5A5A5) & 0xFFFFFFFF,
                  ((s << 13) ^ (s >> 7)) & 0xFFFFFFFF]

    def step(self) -> int:
        a, b, c, d = self.s
        a = (a + b) & 0xFFFFFFFF
        c = (c ^ d) & 0xFFFFFFFF
        b = ((b << 13) | (b >> 19)) & 0xFFFFFFFF
        d = ((d << 7) | (d >> 25)) & 0xFFFFFFFF
        a ^= c
        b = (b + d) & 0xFFFFFFFF
        self.s = [a, b, c, d]
        return (a ^ b ^ c ^ d) & 0xFFFFFFFF


# ---------------------------------------------------------------------------
#  Polar code: frozen bit selection via Bhattacharyya recursion
# ---------------------------------------------------------------------------

def bhattacharyya_polar(n: int, design_ebn0_db: float) -> np.ndarray:
    """
    Return Bhattacharyya parameters for N synthetic channels.
    Indices with smaller Z are more reliable.
    """
    # channel parameter at design SNR
    ebn0 = 10 ** (design_ebn0_db / 10.0)
    z = [math.exp(-ebn0)]  # Z of single BSC-equivalent channel
    while len(z) < n:
        new = []
        for zi in z:
            new.append(2 * zi - zi * zi)  # worse channel
            new.append(zi * zi)           # better channel
        z = new
    return np.array(z[:n])


def select_frozen(n: int, k: int, design_ebn0_db: float = 2.0) -> np.ndarray:
    """Return boolean array of length N; True = frozen, False = info."""
    z = bhattacharyya_polar(n, design_ebn0_db)
    order = np.argsort(z)          # most reliable first
    info_positions = order[:k]     # pick K best for info
    frozen = np.ones(n, dtype=bool)
    frozen[info_positions] = False
    return frozen


def bhattacharyya_punct(n: int, design_ebn0_db: float,
                        keep_mask: np.ndarray) -> np.ndarray:
    """
    Puncturing-aware Bhattacharyya Z values per u-channel.

    Initial z[i] per OUTPUT-position x_i:
      * kept (keep_mask[i] == True)     : z = exp(-Es/N0)
      * punctured (keep_mask[i] == False): z = 1  (total erasure)

    Recursion follows the same butterfly pattern as polar_encode() (which
    is self-inverse over GF(2)), using the BEC-like asymmetric rules:
      W- : z <- z_a + z_b - z_a * z_b   (worse channel)
      W+ : z <- z_a * z_b               (better channel)
    After log2(n) levels, z[i] is the Z of the i-th virtual u-channel.
    """
    ebn0 = 10 ** (design_ebn0_db / 10.0)
    z0 = math.exp(-ebn0)
    z = np.where(keep_mask, z0, 1.0).astype(np.float64)

    stride = 1
    while stride < n:
        for i in range(0, n, 2 * stride):
            for j in range(stride):
                a = z[i + j]
                b = z[i + j + stride]
                z[i + j]          = a + b - a * b
                z[i + j + stride] = a * b
        stride *= 2

    # Bit-reverse the index to match our encoder's u-ordering convention
    # (aligns with bhattacharyya_polar() when keep_mask is all True).
    depth = int(math.log2(n))
    bit_rev = np.zeros(n, dtype=np.int64)
    for i in range(n):
        r = 0
        v = i
        for _ in range(depth):
            r = (r << 1) | (v & 1)
            v >>= 1
        bit_rev[i] = r
    return z[bit_rev]


def select_frozen_punct(n: int, k: int,
                        design_ebn0_db: float,
                        keep_mask: np.ndarray) -> np.ndarray:
    """Puncturing-aware frozen selection."""
    z = bhattacharyya_punct(n, design_ebn0_db, keep_mask)
    order = np.argsort(z)
    info_positions = order[:k]
    frozen = np.ones(n, dtype=bool)
    frozen[info_positions] = False
    return frozen


# ---------------------------------------------------------------------------
#  Polar encoder  (Arikan kernel F = [[1,0],[1,1]], Kronecker applied)
# ---------------------------------------------------------------------------

def polar_encode(u: np.ndarray) -> np.ndarray:
    """In-place-style Polar encoding: x = u * F^{kron n}."""
    n = len(u)
    x = u.copy().astype(np.uint8)
    stride = 1
    while stride < n:
        for i in range(0, n, 2 * stride):
            for j in range(stride):
                x[i + j] ^= x[i + j + stride]
        stride *= 2
    return x


# ---------------------------------------------------------------------------
#  Fractal Rate Expansion: 128 -> 688 via ARX128-keyed permuted repetition
#
#  Design:
#    * Each coded bit is ONE polar bit (no XOR mixing). Decoder is a trivial
#      matched-filter LLR sum per polar index -- TPE-friendly, zero BP.
#    * ARX128 PRNG produces a deterministic permutation of the index pool
#      [0..N_POLAR-1] repeated ceil(N_CODED/N_POLAR) times, then truncated.
#    * Guarantees balanced repetition (max_count - min_count <= 1) and
#      spreads repeats across time to decorrelate burst jammers.
# ---------------------------------------------------------------------------

def build_fractal_masks(seed: int = 0xDEADBEEF) -> np.ndarray:
    """
    Return an int array of shape (N_CODED,) where masks[i] gives the polar
    index whose value is placed at coded position i.

    Construction: stack ceil(N_CODED/N_POLAR) copies of [0..127], shuffle the
    pool with ARX128 (Fisher-Yates), then truncate to N_CODED.
    """
    rng = ARX128(seed)

    # Exact balanced multiset:
    #   low_reps = floor(N_CODED/N_POLAR), high_reps = low_reps + 1
    #   n_high indices get high_reps copies, rest get low_reps copies.
    low_reps = N_CODED // N_POLAR
    n_high = N_CODED - low_reps * N_POLAR            # indices with +1 copy
    # Pick which indices get the extra copy via an ARX-shuffled 0..N_POLAR-1.
    idx_order = np.arange(N_POLAR, dtype=np.int32)
    for i in range(N_POLAR - 1, 0, -1):
        j = rng.step() % (i + 1)
        idx_order[i], idx_order[j] = idx_order[j], idx_order[i]
    high_set = idx_order[:n_high]

    pool = np.empty(N_CODED, dtype=np.int32)
    k = 0
    for idx in range(N_POLAR):
        r = low_reps + (1 if idx in set(high_set.tolist()) else 0)
        pool[k:k + r] = idx
        k += r
    assert k == N_CODED

    # Fisher-Yates shuffle positions so repeats are time-spread.
    for i in range(N_CODED - 1, 0, -1):
        j = rng.step() % (i + 1)
        pool[i], pool[j] = pool[j], pool[i]

    masks = pool

    # sanity: balanced repetition, every polar bit covered
    counts = np.bincount(masks, minlength=N_POLAR)
    assert counts.min() >= 1, f"uncovered polar bit (min={counts.min()})"
    assert counts.max() - counts.min() <= 1, \
        f"unbalanced rep: min={counts.min()} max={counts.max()}"
    return masks


def fractal_expand(polar_bits: np.ndarray, masks: np.ndarray) -> np.ndarray:
    """128 polar bits -> 688 coded bits via permuted repetition."""
    return polar_bits[masks].astype(np.uint8)


def fractal_combine_llr(rx_llr: np.ndarray, masks: np.ndarray) -> np.ndarray:
    """
    Matched-filter combine: sum LLRs landing on each polar index.
    This is the ML soft-combiner for repetition over AWGN.
    """
    combined = np.zeros(N_POLAR, dtype=np.float64)
    # np.add.at is the unbuffered indexed accumulation (correct for duplicates)
    np.add.at(combined, masks, rx_llr)
    return combined


# ---------------------------------------------------------------------------
#  Puncturing-mode rate matching: Mother Polar N_INNER -> N_CODED chips
#
#  Design:
#    * ARX128 selects a deterministic subset of N_INNER - N_CODED positions
#      to PUNCTURE (discard). No repetition -- the Polar kernel itself
#      delivers all coding gain.
#    * Encoder: compute full-length polar codeword, output the non-punctured
#      positions in canonical (ascending-index) order.
#    * Decoder: build a length-N_INNER LLR vector with 0 (erasure, no info)
#      at punctured positions and the received LLR at the kept positions,
#      then run the same SCL as the repetition path.
#    * Zero LUT memory, ARX-keyed (cryptographic), TPE-friendly.
# ---------------------------------------------------------------------------

def build_puncture_mask(n_inner: int,
                        n_coded: int,
                        seed: int = 0xDEADBEEF) -> Tuple[np.ndarray, np.ndarray]:
    """
    Return (keep_mask, keep_positions):
      keep_mask        bool array of length n_inner; True = transmitted,
                       False = punctured (decoder sees LLR=0 here).
      keep_positions   int array of length n_coded giving the ASCENDING
                       indices of the n_coded transmitted bits, i.e.
                       where the n_coded received LLRs belong in the
                       length-n_inner buffer at the decoder.

    Construction:
      * Fisher-Yates shuffle [0..n_inner-1] with ARX128.
      * First n_coded shuffled indices are "keep"; the rest are punctured.
      * We return keep_positions SORTED so the encoder/decoder agree on
        which chip index corresponds to which Polar output position.
    """
    assert 0 < n_coded <= n_inner
    rng = ARX128(seed)
    order = np.arange(n_inner, dtype=np.int32)
    for i in range(n_inner - 1, 0, -1):
        j = rng.step() % (i + 1)
        order[i], order[j] = order[j], order[i]
    keep_positions = np.sort(order[:n_coded]).astype(np.int32)
    keep_mask = np.zeros(n_inner, dtype=bool)
    keep_mask[keep_positions] = True
    return keep_mask, keep_positions


# ---------------------------------------------------------------------------
#  Polar SC decoder (integer, TPE-style f/g)
# ---------------------------------------------------------------------------

def f_node(a: float, b: float) -> float:
    """f = sign(a)*sign(b)*min(|a|,|b|)"""
    sa = 1.0 if a >= 0 else -1.0
    sb = 1.0 if b >= 0 else -1.0
    return sa * sb * min(abs(a), abs(b))


def g_node(a: float, b: float, u: int) -> float:
    """g = (1 - 2u)*a + b"""
    return (a if u == 0 else -a) + b


def sc_decode(llr_in: np.ndarray, frozen: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Standard Polar SC decoder.
    Returns (decoded_u_hat, decoded_x_hat, decision_llr).
    decision_llr[i] = the LLR at the leaf at the moment u_hat[i] was decided
    (i.e. SC reliability, not channel reliability).
    """
    n = len(llr_in)
    depth = int(math.log2(n))

    # stage LLR buffers
    llr = np.zeros((depth + 1, n))
    llr[depth] = llr_in
    u_hat = np.zeros(n, dtype=np.uint8)
    decision_llr = np.zeros(n, dtype=np.float64)
    # partial sums per stage
    ps = np.zeros((depth + 1, n), dtype=np.uint8)

    def recurse(stage: int, start: int, length: int):
        if length == 1:
            decision_llr[start] = llr[stage, start]
            if frozen[start]:
                u_hat[start] = 0
            else:
                u_hat[start] = 0 if llr[stage, start] >= 0 else 1
            ps[stage, start] = u_hat[start]
            return

        half = length // 2
        # f-step: produce left-child LLRs
        for i in range(half):
            a = llr[stage, start + i]
            b = llr[stage, start + i + half]
            llr[stage - 1, start + i] = f_node(a, b)
        recurse(stage - 1, start, half)

        # g-step: right-child LLRs
        for i in range(half):
            a = llr[stage, start + i]
            b = llr[stage, start + i + half]
            u = ps[stage - 1, start + i]
            llr[stage - 1, start + i + half] = g_node(a, b, int(u))
        recurse(stage - 1, start + half, half)

        # combine partial sums upward
        for i in range(half):
            ps[stage, start + i] = ps[stage - 1, start + i] ^ ps[stage - 1, start + i + half]
            ps[stage, start + i + half] = ps[stage - 1, start + i + half]

    recurse(depth, 0, n)
    x_hat = polar_encode(u_hat)
    return u_hat, x_hat, decision_llr


# ---------------------------------------------------------------------------
#  CRC-aided SC-List (CA-SCL) decoder  (L = 4 default)
#
#  Standard CA-SCL:
#    * Maintain up to L candidate paths, each with its own (llr, ps, u_hat, pm)
#    * At each non-frozen leaf, fork every live path into 2 children
#      (u=0 and u=1); add the "wrong-sign" penalty |LLR| to whichever
#      candidate disagrees with sign(LLR). Keep the L paths with smallest PM.
#    * Frozen leaves: all paths take u=0; add |LLR| if LLR < 0.
#    * At the end, select the path whose (info || CRC) satisfies CRC-16,
#      ties broken by smallest PM. If no path passes, declare failure.
#
#  Memory per path: (depth+1) * N LLRs + (depth+1) * N partial sums + N u_hat
#                 = 8 * 128 * 8B + 8 * 128 * 1B + 128 * 1B  ~= 9 KB (Python)
#  With L=4: ~36 KB — acceptable for simulation, well under 192 KB SRAM.
# ---------------------------------------------------------------------------


@dataclass
class _Path:
    llr: np.ndarray       # shape (depth+1, n)
    ps: np.ndarray        # shape (depth+1, n) uint8
    u_hat: np.ndarray     # shape (n,) uint8
    pm: float             # path metric (sum of wrong-sign |LLR|)

    def clone(self) -> "_Path":
        return _Path(self.llr.copy(), self.ps.copy(),
                     self.u_hat.copy(), self.pm)


def _scl_decode(llr_in: np.ndarray, frozen: np.ndarray,
                L: int) -> List[_Path]:
    """Run CA-SCL and return the final L surviving paths (sorted by PM)."""
    n = len(llr_in)
    depth = int(math.log2(n))

    # Seed with a single path.
    root = _Path(
        llr=np.zeros((depth + 1, n), dtype=np.float64),
        ps=np.zeros((depth + 1, n), dtype=np.uint8),
        u_hat=np.zeros(n, dtype=np.uint8),
        pm=0.0,
    )
    root.llr[depth] = llr_in
    paths: List[_Path] = [root]

    def recurse(start: int, length: int, stage: int):
        nonlocal paths
        if length == 1:
            if frozen[start]:
                # no fork; all paths take u=0
                for p in paths:
                    v = p.llr[stage, start]
                    if v < 0.0:
                        p.pm += -v
                    p.u_hat[start] = 0
                    p.ps[stage, start] = 0
                return

            # Non-frozen: fork every path into 2 candidates.
            cand: List[_Path] = []
            for p in paths:
                v = p.llr[stage, start]
                abs_v = abs(v)
                # u=0 candidate
                c0 = p.clone()
                c0.u_hat[start] = 0
                c0.ps[stage, start] = 0
                if v < 0.0:           # sign says 1 but we picked 0
                    c0.pm += abs_v
                # u=1 candidate
                c1 = p.clone()
                c1.u_hat[start] = 1
                c1.ps[stage, start] = 1
                if v >= 0.0:          # sign says 0 but we picked 1
                    c1.pm += abs_v
                cand.append(c0)
                cand.append(c1)
            cand.sort(key=lambda x: x.pm)
            paths = cand[:L]
            return

        half = length // 2
        # f-step on every live path
        for p in paths:
            for i in range(half):
                a = p.llr[stage, start + i]
                b = p.llr[stage, start + i + half]
                p.llr[stage - 1, start + i] = f_node(a, b)
        recurse(start, half, stage - 1)

        # g-step (path-specific because it depends on partial sums)
        for p in paths:
            for i in range(half):
                a = p.llr[stage, start + i]
                b = p.llr[stage, start + i + half]
                u = int(p.ps[stage - 1, start + i])
                p.llr[stage - 1, start + i + half] = g_node(a, b, u)
        recurse(start + half, half, stage - 1)

        # combine partial sums upward
        for p in paths:
            for i in range(half):
                p.ps[stage, start + i] = (
                    p.ps[stage - 1, start + i] ^
                    p.ps[stage - 1, start + i + half])
                p.ps[stage, start + i + half] = \
                    p.ps[stage - 1, start + i + half]

    recurse(0, n, depth)
    paths.sort(key=lambda x: x.pm)
    return paths


def scl_decode_with_crc(
    llr_in: np.ndarray,
    frozen: np.ndarray,
    L: int = 4,
) -> Tuple[bool, np.ndarray, int]:
    """
    CA-SCL outer wrapper.
    Returns (ok, info_bits[64], winner_rank) where winner_rank is the
    0-based PM-rank of the selected (CRC-passing) path, or -1 on failure.
    """
    paths = _scl_decode(llr_in, frozen, L)
    info_slots = np.where(~frozen)[0]

    # Scan paths in order of increasing PM; pick first CRC-pass.
    for rank, p in enumerate(paths):
        info = p.u_hat[info_slots]
        rx_info = info[:K_INFO]
        rx_crc  = info[K_INFO:]
        if np.array_equal(crc16_ccitt(rx_info), rx_crc):
            return True, rx_info, rank

    # No path passed CRC; return the best-PM info anyway (for BER accounting).
    best = paths[0]
    info = best.u_hat[info_slots]
    return False, info[:K_INFO], -1


# ---------------------------------------------------------------------------
#  TX / RX full pipeline
# ---------------------------------------------------------------------------

@dataclass
class Codec:
    frozen: np.ndarray
    # Repetition mode: index map polar_idx[N_CODED]. Puncturing mode: unused.
    masks: np.ndarray
    mode: str = "rep"          # "rep" | "punct"
    # Puncturing mode: bool[N_POLAR] keep mask + sorted keep indices[N_CODED].
    keep_mask: np.ndarray = None
    keep_positions: np.ndarray = None

    @classmethod
    def build(cls, seed: int = 0xDEADBEEF,
              target_ebn0_db: float = 2.5,
              mode: str = "rep") -> "Codec":
        """
        Build a codec for the currently configured (N_POLAR, N_CODED).

        mode="rep"   : balanced permuted-repetition expansion (N_POLAR<=N_CODED)
        mode="punct" : Mother-Polar puncturing (N_POLAR>=N_CODED); N_POLAR-N_CODED
                       positions are erased by the channel model.
        """
        rate_coded = K_INFO / N_CODED
        ebn0_lin = 10 ** (target_ebn0_db / 10.0)

        if mode == "rep":
            # Bhattacharyya design SNR = post-combining polar-input Es/N0
            polar_esn0_lin = REP_AVG * rate_coded * ebn0_lin
            polar_esn0_db = 10.0 * math.log10(polar_esn0_lin)
            frozen = select_frozen(N_POLAR, K_PAYLOAD, polar_esn0_db)
            masks = build_fractal_masks(seed)
            return cls(frozen=frozen, masks=masks, mode="rep")

        elif mode == "punct":
            assert N_POLAR >= N_CODED, \
                f"puncturing requires N_POLAR ({N_POLAR}) >= N_CODED ({N_CODED})"
            # Build the ARX-keyed puncture pattern FIRST, then compute
            # puncturing-aware Bhattacharyya so the frozen set accounts for
            # which output positions are erased.
            keep_mask, keep_positions = build_puncture_mask(
                N_POLAR, N_CODED, seed=seed)
            # Design SNR: per-chip Es/N0 at target operating Eb/N0.
            polar_esn0_lin = rate_coded * ebn0_lin
            polar_esn0_db = 10.0 * math.log10(polar_esn0_lin)
            frozen = select_frozen_punct(N_POLAR, K_PAYLOAD,
                                         polar_esn0_db, keep_mask)
            return cls(frozen=frozen, masks=np.array([], dtype=np.int32),
                       mode="punct",
                       keep_mask=keep_mask,
                       keep_positions=keep_positions)
        else:
            raise ValueError(f"unknown mode {mode!r}")


def encode(info: np.ndarray, codec: Codec) -> np.ndarray:
    """K_INFO info bits -> N_CODED chips."""
    assert len(info) == K_INFO
    crc = crc16_ccitt(info)
    payload = np.concatenate([info, crc])         # K_PAYLOAD bits

    u = np.zeros(N_POLAR, dtype=np.uint8)
    info_slots = np.where(~codec.frozen)[0]
    u[info_slots] = payload

    polar_bits = polar_encode(u)                  # N_POLAR bits

    if codec.mode == "rep":
        return fractal_expand(polar_bits, codec.masks)
    # puncturing: pick the kept positions in sorted index order
    return polar_bits[codec.keep_positions].astype(np.uint8)


def decode(rx_llr_coded: np.ndarray, codec: Codec,
           L: int = 4) -> Tuple[bool, np.ndarray, int]:
    """N_CODED soft LLRs -> K_INFO info bits, success flag, winner rank."""
    if codec.mode == "rep":
        polar_llr = fractal_combine_llr(rx_llr_coded, codec.masks)
    else:
        # puncturing: punctured positions = 0 (no info); received fill kept.
        polar_llr = np.zeros(N_POLAR, dtype=np.float64)
        polar_llr[codec.keep_positions] = rx_llr_coded
    return scl_decode_with_crc(polar_llr, codec.frozen, L=L)


# ---------------------------------------------------------------------------
#  AWGN channel
# ---------------------------------------------------------------------------

def awgn_bpsk(coded_bits: np.ndarray, ebn0_db: float, rate: float,
              rng: np.random.Generator) -> np.ndarray:
    """BPSK: 0 -> +1, 1 -> -1. Returns LLR = 2*y/sigma^2."""
    sym = 1.0 - 2.0 * coded_bits.astype(np.float64)
    ebn0 = 10 ** (ebn0_db / 10.0)
    # sigma^2 relative to bit energy = 1:
    #   Es/N0 = R * Eb/N0
    esn0 = rate * ebn0
    sigma = math.sqrt(1.0 / (2.0 * esn0))
    noise = rng.standard_normal(len(sym)) * sigma
    y = sym + noise
    llr = 2.0 * y / (sigma * sigma)
    return llr


# ---------------------------------------------------------------------------
#  Simulation loop
# ---------------------------------------------------------------------------

def run_point(ebn0_db: float, trials: int, codec: Codec,
              seed: int = 0xC0FFEE, L: int = 4) -> dict:
    """
    Simulate one Eb/N0 point.

    Reports:
      bler           : block-error rate on the true info bits
      ber            : uncoded info BER on the true info bits
      crc_fail_rate  : fraction of frames where no SCL path passed CRC
      crc_fp_rate    : fraction of "CRC pass" frames where info was still wrong
                        (CRC false-positive)
      rank_hist      : histogram of winning path rank (0 = best PM)
      decode_ms_avg  : mean wall-clock decode time per frame
    """
    rng = np.random.default_rng(seed)
    rate = K_INFO / N_CODED

    errors_block = 0      # wrong info bits (ground truth)
    errors_bit = 0
    crc_fail = 0          # SCL returned ok=False
    crc_fp = 0            # SCL returned ok=True but info differs from truth
    decode_time_total = 0.0
    rank_hist = [0] * L

    for t in range(trials):
        info = rng.integers(0, 2, size=K_INFO, dtype=np.uint8)
        coded = encode(info, codec)
        llr = awgn_bpsk(coded, ebn0_db, rate, rng)

        t0 = time.perf_counter()
        ok, info_hat, rank = decode(llr, codec, L=L)
        decode_time_total += time.perf_counter() - t0

        truth_ok = np.array_equal(info_hat, info)

        if ok:
            rank_hist[rank] += 1
            if not truth_ok:
                crc_fp += 1
                errors_block += 1
                errors_bit += int(np.sum(info_hat != info))
        else:
            crc_fail += 1
            if not truth_ok:
                errors_block += 1
                errors_bit += int(np.sum(info_hat != info))

    return dict(
        ebno=ebn0_db,
        trials=trials,
        bler=errors_block / trials,
        ber=errors_bit / (trials * K_INFO),
        crc_fail_rate=crc_fail / trials,
        crc_fp_rate=(crc_fp / (trials - crc_fail)) if (trials - crc_fail) else 0.0,
        rank_hist=rank_hist,
        decode_ms_avg=1000.0 * decode_time_total / trials,
    )


# ---------------------------------------------------------------------------
#  Verification / self-test harness
# ---------------------------------------------------------------------------

def selftest_noiseless(codec: Codec, L: int = 4, n_trials: int = 64) -> None:
    """encode -> hard-LLR (no noise) -> decode must be lossless."""
    rng = np.random.default_rng(0xBADC0DE)
    fails = 0
    for _ in range(n_trials):
        info = rng.integers(0, 2, size=K_INFO, dtype=np.uint8)
        coded = encode(info, codec)
        llr = np.where(coded == 0, 20.0, -20.0)
        ok, info_hat, rank = decode(llr, codec, L=L)
        if not ok or not np.array_equal(info, info_hat):
            fails += 1
    assert fails == 0, f"noiseless self-test FAILED ({fails}/{n_trials})"
    print(f"  [selftest] noiseless lossless ............ PASS "
          f"({n_trials}/{n_trials})")


def selftest_polar_identity(design_db: float = 0.0, n_trials: int = 64) -> None:
    """Direct Polar(128,80) SCL at very high SNR must be lossless."""
    frozen = select_frozen(N_POLAR, K_PAYLOAD, design_db)
    info_slots = np.where(~frozen)[0]
    rng = np.random.default_rng(0xFEED)
    fails = 0
    for _ in range(n_trials):
        payload = rng.integers(0, 2, size=K_PAYLOAD, dtype=np.uint8)
        u = np.zeros(N_POLAR, dtype=np.uint8)
        u[info_slots] = payload
        x = polar_encode(u)
        llr = np.where(x == 0, 50.0, -50.0)
        paths = _scl_decode(llr, frozen, L=4)
        got = paths[0].u_hat[info_slots]
        if not np.array_equal(got, payload):
            fails += 1
    assert fails == 0, f"polar identity self-test FAILED ({fails}/{n_trials})"
    print(f"  [selftest] polar(128,80) noiseless ....... PASS "
          f"({n_trials}/{n_trials})")


def selftest_crc(n_trials: int = 1000) -> None:
    """crc16 check must accept matched bits and reject corrupted ones."""
    rng = np.random.default_rng(0xCAFE)
    accepts = 0
    false_accepts = 0
    for _ in range(n_trials):
        info = rng.integers(0, 2, size=K_INFO, dtype=np.uint8)
        crc = crc16_ccitt(info)
        if np.array_equal(crc16_ccitt(info), crc):
            accepts += 1
        # corrupt a random bit and ensure rejection
        bad = info.copy()
        bad[rng.integers(0, K_INFO)] ^= 1
        if np.array_equal(crc16_ccitt(bad), crc):
            false_accepts += 1
    assert accepts == n_trials
    assert false_accepts == 0, f"CRC accepted {false_accepts} corrupted frames"
    print(f"  [selftest] crc16 accept/reject ........... PASS "
          f"({n_trials} accepts, 0 false-accepts)")


def selftest_arx128() -> None:
    """ARX128 must be deterministic and non-degenerate."""
    a = ARX128(0x12345678)
    b = ARX128(0x12345678)
    seq_a = [a.step() for _ in range(1024)]
    seq_b = [b.step() for _ in range(1024)]
    assert seq_a == seq_b, "ARX128 not deterministic"
    # non-degeneracy: at least 1000 unique 32-bit outputs in 1024 draws
    assert len(set(seq_a)) > 1000, \
        f"ARX128 degenerate: only {len(set(seq_a))} unique outputs"
    print(f"  [selftest] ARX128 determinism/entropy .... PASS "
          f"({len(set(seq_a))}/1024 unique)")


def selftest_mask_balance(codec: Codec) -> None:
    """Rep-map balance (spread <= 1) OR puncture-mask integrity."""
    if codec.mode == "rep":
        counts = np.bincount(codec.masks, minlength=N_POLAR)
        low = N_CODED // N_POLAR
        high = low + (1 if (N_CODED % N_POLAR) else 0)
        assert counts.max() - counts.min() <= 1 and counts.min() >= low, \
            f"unbalanced mask: {counts.min()}..{counts.max()} (want {low}..{high})"
        n_high = (counts == high).sum()
        print(f"  [selftest] fractal mask balance .......... PASS "
              f"(rep min={counts.min()}, max={counts.max()}, "
              f"n_high={n_high})")
    else:
        assert codec.keep_mask.sum() == N_CODED, \
            f"keep count {int(codec.keep_mask.sum())} != N_CODED {N_CODED}"
        assert len(codec.keep_positions) == N_CODED
        assert np.all(np.diff(codec.keep_positions) > 0), \
            "keep_positions must be strictly increasing"
        print(f"  [selftest] puncture mask integrity ....... PASS "
              f"(keep={int(codec.keep_mask.sum())}, "
              f"punct={N_POLAR - int(codec.keep_mask.sum())})")


def run_selftests(codec: Codec) -> None:
    print("-" * 64)
    print(" SELF-TESTS")
    print("-" * 64)
    selftest_arx128()
    selftest_crc()
    selftest_mask_balance(codec)
    selftest_polar_identity()
    selftest_noiseless(codec)
    print()


def uncoded_bpsk_ber(ebn0_db: float) -> float:
    """Closed form: Q(sqrt(2 Eb/N0))."""
    ebn0 = 10 ** (ebn0_db / 10.0)
    from math import erfc, sqrt
    return 0.5 * erfc(sqrt(ebn0))


def banner(codec: Codec) -> None:
    n_info_slots = int(np.sum(~codec.frozen))
    print("=" * 64)
    print(" HTS-HFC v2  Reference Simulator")
    print("=" * 64)
    print(f"  K_INFO            = {K_INFO}")
    print(f"  CRC_BITS          = {CRC_BITS}")
    print(f"  K_PAYLOAD         = {K_PAYLOAD}  (info+CRC)")
    print(f"  N_POLAR           = {N_POLAR}")
    print(f"  N_CODED           = {N_CODED}")
    print(f"  Rep expansion avg = {REP_AVG:.3f}  (coded bits per polar bit)")
    print(f"  Polar info slots  = {n_info_slots}")
    print(f"  Overall rate R    = {K_INFO / N_CODED:.4f}")
    print("=" * 64)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true",
                    help="fast smoke test (500 trials, 3 SNR points)")
    ap.add_argument("--ebno", type=float, default=None,
                    help="single Eb/N0 point (dB)")
    ap.add_argument("--trials", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=0xDEADBEEF)
    ap.add_argument("-L", "--list-size", type=int, default=4,
                    help="SCL list size (default 4)")
    ap.add_argument("--n-polar", type=int, default=128,
                    choices=[64, 128, 256, 512, 1024],
                    help="inner Polar code length (default 128)")
    ap.add_argument("--mode", choices=["rep", "punct"], default="rep",
                    help="rate-matching mode: rep (N<=688) or punct (N>=688)")
    ap.add_argument("--verify", action="store_true",
                    help="run self-test suite only (no SNR sweep)")
    ap.add_argument("--waterfall", action="store_true",
                    help="dense sweep 1.5..4.0 dB by 0.25 dB for BER curve")
    args = ap.parse_args()

    configure_dimensions(args.n_polar)
    print(f"Building codec (N_inner={N_POLAR}, mode={args.mode}) ...")
    codec = Codec.build(seed=args.seed, target_ebn0_db=2.5, mode=args.mode)
    banner(codec)
    print(f"  SCL list size L   = {args.list_size}")
    print("=" * 64)
    print()

    run_selftests(codec)
    if args.verify:
        return 0

    if args.ebno is not None:
        pts = [args.ebno]
        trials = args.trials
    elif args.quick:
        pts = [1.0, 2.0, 3.0]
        trials = 500
    elif args.waterfall:
        pts = [1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0]
        trials = args.trials
    else:
        pts = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
        trials = args.trials

    print(f"Running: trials={trials} per point, L={args.list_size}")
    print(f"{'Eb/N0':>7} {'BLER':>9} {'BER':>11} {'uncoded':>10} "
          f"{'CRC_fail':>9} {'CRC_FP':>9} {'rank0%':>7} {'ms':>8}")
    print("-" * 80)
    results = []
    for eb in pts:
        r = run_point(eb, trials, codec,
                      seed=0xC0FFEE + int(eb * 100),
                      L=args.list_size)
        results.append(r)
        rank0 = r['rank_hist'][0] / max(1, sum(r['rank_hist']))
        unc = uncoded_bpsk_ber(eb)
        print(f"{r['ebno']:>7.2f} {r['bler']:>9.4f} {r['ber']:>11.4e} "
              f"{unc:>10.4e} {r['crc_fail_rate']:>9.4f} "
              f"{r['crc_fp_rate']:>9.4f} {100*rank0:>6.1f}% "
              f"{r['decode_ms_avg']:>8.2f}")
    print()
    print("Reference targets (K=64, N=688):")
    print("  Shannon finite-length limit : Eb/N0 ~= 1.8 dB @ BLER 1e-3")
    print("  CRC-Polar-SCL L=8           : Eb/N0 ~= 2.0 dB @ BLER 1e-3")
    print("  HTS-HFC v2 design target    : Eb/N0 <= 2.3 dB @ BLER 1e-3")
    print()
    print("Column legend:")
    print("  uncoded  : closed-form uncoded-BPSK BER = Q(sqrt(2 Eb/N0))")
    print("  CRC_fail : fraction of frames where no SCL path passed CRC")
    print("  CRC_FP   : false-positive rate of CRC-pass claims vs truth")
    print("  rank0%   : fraction of CRC-pass wins on the best-PM path")
    return 0


if __name__ == "__main__":
    sys.exit(main())
